replicaCount: 2

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  size: 15Gi
  storageClass: "local-path"

ingress:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
