apiVersion: v1
kind: Service
metadata:
  name: openwebui
  labels:
    app.kubernetes.io/name: openwebui
spec:
  selector:
    app.kubernetes.io/name: openwebui
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
