apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ollama-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: ollama.rules
      rules:
        # --- Per-pod con LIMITS ---
        - alert: OllamaHighMemoryUsagePod
          expr: |
            100 *
            sum by (pod) (container_memory_working_set_bytes{namespace="ai",pod=~"ollama.*",container!="" ,container!="POD"})
            /
            sum by (pod) (kube_pod_container_resource_limits{namespace="ai",resource="memory",pod=~"ollama.*"})
            > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Ollama RAM alta ({{ $labels.pod }})"
            description: "Uso de memoria >80% del límite por 5m."

        # --- Per-pod SIN limits: usa requests como baseline ---
        - alert: OllamaHighMemoryUsagePodNoLimit
          expr: |
            100 *
            sum by (pod) (container_memory_working_set_bytes{namespace="ai",pod=~"ollama.*",container!="" ,container!="POD"})
            /
            sum by (pod) (kube_pod_container_resource_requests{namespace="ai",resource="memory",pod=~"ollama.*"})
            > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Ollama RAM alta sin límite ({{ $labels.pod }})"
            description: "Sin límite de memoria; comparado contra requests >80% por 5m."

        # --- Agregado (general para todos) con LIMITS ---
        - alert: OllamaHighMemoryUsageTotal
          expr: |
            100 *
            sum(container_memory_working_set_bytes{namespace="ai",pod=~"ollama.*",container!="" ,container!="POD"})
            /
            sum(kube_pod_container_resource_limits{namespace="ai",resource="memory",pod=~"ollama.*"})
            > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Ollama RAM total >80%"
            description: "Suma de memoria (todos los pods Ollama) supera 80% del límite por 5m."

        # --- Agregado SIN limits: usa requests ---
        - alert: OllamaHighMemoryUsageTotalNoLimit
          expr: |
            100 *
            sum(container_memory_working_set_bytes{namespace="ai",pod=~"ollama.*",container!="" ,container!="POD"})
            /
            sum(kube_pod_container_resource_requests{namespace="ai",resource="memory",pod=~"ollama.*"})
            > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Ollama RAM total >80% (sin límites)"
            description: "No hay límites; se usa la suma de requests como baseline por 5m."
