apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  labels:
    app.kubernetes.io/name: ollama
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
