apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
spec:
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 11434
      protocol: TCP
