server:
  extraArgs: ["--insecure"]
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts: [ "argocd.hw-fng.com" ]
    paths: [ "/" ]
    tls:
      - hosts: [ "argocd.hw-fng.com" ]
        secretName: argocd-tls
