apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.0.0
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts: [ "prometheus.hw-fng.com" ]
            tls:
              - hosts: [ "prometheus.hw-fng.com" ]
                secretName: prometheus-tls
          prometheusSpec:
            retention: 24h
            resources:
              requests: { cpu: 200m, memory: 512Mi }
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  resources:
                    requests: { storage: 8Gi }

        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts: [ "grafana.hw-fng.com" ]
            tls:
              - hosts: [ "grafana.hw-fng.com" ]
                secretName: grafana-tls
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
