apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: otel-collector
  namespaceSelector:
    matchNames: ["monitoring"]
  endpoints:
    - port: prom-exp
      path: /metrics
      interval: 15s
