apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.0.1
    chart: prometheus-blackbox-exporter
    helm:
      values: |
        serviceMonitor:
          enabled: true
          namespace: monitoring
          targets:
            - name: ollama-api
              url: http://ollama.ai.svc.cluster.local:11434/api/tags
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
