apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.4
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          useTestSchema: true
          server:
            http_listen_port: 3100
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          rulerConfig:
            storage:
              type: local
              local:
                directory: /var/loki/rules
        singleBinary:
          replicas: 1
          securityContext:
            readOnlyRootFilesystem: false
          persistence:
            enabled: false
          extraVolumes:
            - name: loki-data
              emptyDir: {}
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        memcached:
          enabled: false
        memcachedExporter:
          enabled: false
        gateway:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
        test:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
