apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.otwld.com/
    chart: ollama
    targetRevision: 1.26.0
    helm:
      values: |       
        replicaCount: 2
        ollama:
          models:
            create:
              - name: llama3-8b-q3-ctx2k
                template: |
                  FROM llama3:8b-instruct-q3_K_M
                  PARAMETER num_ctx 2048
            run:
              - llama3-8b-q3-ctx2k
            pull:
              - llama3:8b-instruct-q3_K_M
        persistentVolume:
          enabled: true
          size: 30Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true